In [25]:
import pandas as pd
df = pd.read_csv(r"Superstore sales dataset.csv")
df.shape

(9994, 21)

In [26]:
df.size

209874

In [29]:
df.head(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

In [30]:
df.tail(6)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9993,9994,CA-2017-119914,4/5/2017,9/5/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.16,2,0.0,72.948

In [32]:
df.index

RangeIndex(start=0, stop=9994, step=1)

In [33]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [36]:
df[['Row ID','Order ID','Sales']].head(6)

   Row ID        Order ID     Sales
0       1  CA-2016-152156  261.9600
1       2  CA-2016-152156  731.9400
2       3  CA-2016-138688   14.6200
3       4  US-2015-108966  957.5775
4       5  US-2015-108966   22.3680
5       6  CA-2014-115812   48.8600

In [38]:
# df.iloc[rows,columns]

In [45]:
df.iloc[1:5,[1,2,3]]

         Order ID  Order Date   Ship Date
1  CA-2016-152156   8/11/2016  11/11/2016
2  CA-2016-138688   12/6/2016   16/6/2016
3  US-2015-108966  11/10/2015  18/10/2015
4  US-2015-108966  11/10/2015  18/10/2015

In [46]:
df.dtypes

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [49]:
np.iinfo(np.int8)

NameError: name 'np' is not defined

In [50]:
df.select_dtypes(include=['int64','float64']).head(2)

   Row ID  Postal Code   Sales  Quantity  Discount    Profit
0       1        42420  261.96         2       0.0   41.9136
1       2        42420  731.94         3       0.0  219.5820

In [53]:
# df.select_dtypes(include=['str']).shape

In [57]:
set_df=df.iloc[0:5,0:5].copy()
print(subset_df)

   Row ID        Order ID  Order Date   Ship Date       Ship Mode
0       1  CA-2016-152156   8/11/2016  11/11/2016    Second Class
1       2  CA-2016-152156   8/11/2016  11/11/2016    Second Class
2       3  CA-2016-138688   12/6/2016   16/6/2016    Second Class
3       4  US-2015-108966  11/10/2015  18/10/2015  Standard Class
4       5  US-2015-108966  11/10/2015  18/10/2015  Standard Class

In [58]:
set_df[['Row ID','Order ID','Ship Mode','Ship Date']].min()

Row ID                    1
Order ID     CA-2016-138688
Ship Mode      Second Class
Ship Date        11/11/2016
dtype: object

In [59]:
df[['Sales']].mean()

Sales    229.858001
dtype: float64

In [60]:
df['Ship Mode'].str.upper().head(2)

0    SECOND CLASS
1    SECOND CLASS
Name: Ship Mode, dtype: object

In [61]:
df['Ship Mode'].str.lower().head(2)

0    second class
1    second class
Name: Ship Mode, dtype: object

In [62]:
df['Ship Mode'].str.capitalize().head(2)

0    Second class
1    Second class
Name: Ship Mode, dtype: object

In [63]:
df['Ship Mode'].str.title().head(2)

0    Second Class
1    Second Class
Name: Ship Mode, dtype: object

In [64]:
"data Science".capitalize()

'Data science'

In [65]:
df['Ship Mode'].str.len().head(2)

0    12
1    12
Name: Ship Mode, dtype: int64

In [66]:
df['Ship Mode'].str.strip().head(2)

0    Second Class
1    Second Class
Name: Ship Mode, dtype: object

In [67]:
df['Ship Mode'].str.split(" ").str[0]

0         Second
1         Second
2         Second
3       Standard
4       Standard
          ...
9989      Second
9990    Standard
9991    Standard
9992    Standard
9993      Second
Name: Ship Mode, Length: 9994, dtype: object

In [68]:
df['Ship Mode'].str.rstrip().head(2)

0    Second Class
1    Second Class
Name: Ship Mode, dtype: object

In [70]:
"91-7338--33".split("-")

['91', '7338', '', '33']

In [71]:
df['Ship Mode'].str.count("Second")

0       1
1       1
2       1
3       0
4       0
       ..
9989    1
9990    0
9991    0
9992    0
9993    1
Name: Ship Mode, Length: 9994, dtype: int64

In [72]:
df['Ship Mode'].str.pad(width=20,side='left',fillchar="-")

0       --------Second Class
1       --------Second Class
2       --------Second Class
3       ------Standard Class
4       ------Standard Class
                ...
9989    --------Second Class
9990    ------Standard Class
9991    ------Standard Class
9992    ------Standard Class
9993    --------Second Class
Name: Ship Mode, Length: 9994, dtype: object

In [73]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [74]:
df.duplicated().sum()

0

In [75]:
df = df.drop_duplicates()

In [77]:
df.rename(columns={'Row ID': 'Row ID 1'}, inplace=True)
print

In [79]:
df.columns

Index(['Row ID 1', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [ ]:
# import pandas as pd

# # 1. Read CSV file
# df = pd.read_csv("Superstore sales dataset(1).csv", encoding="latin1")  # How do you read CSV file?

# # 2. Basic dataset understanding
# df.head()  # How do you see first 5 rows?
# df.tail()  # How do you see last 5 rows?
# df.shape  # How do you check number of rows and columns?
# df.columns  # How do you check all column names?
# df.dtypes  # How do you check data types?
# df.info()  # How do you check full dataset information?
# df.describe()  # How do you get statistical summary?

# # 3. Clean column names
# df.columns = df.columns.str.strip()  # How do you remove spaces from column names?
# df.rename(columns={'ï»¿Row ID': 'Row ID'}, inplace=True)  # How do you rename wrong encoded Row ID column?

# # 4. Missing values and duplicates
# df.isnull().sum()  # How do you check missing values?
# df.isnull().sum().sum()  # How do you check total missing values?
# df.duplicated().sum()  # How do you check duplicate rows?
# df.drop_duplicates(inplace=True)  # How do you remove duplicate rows?

# # 5. Convert date columns
# df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True)  # How do you convert Order Date to datetime?
# df['Ship Date'] = pd.to_datetime(df['Ship Date'], dayfirst=True)  # How do you convert Ship Date to datetime?

# # 6. Create new date columns
# df['Year'] = df['Order Date'].dt.year  # How do you extract year?
# df['Month'] = df['Order Date'].dt.month  # How do you extract month?
# df['Day'] = df['Order Date'].dt.day  # How do you extract day?
# df['Weekday'] = df['Order Date'].dt.day_name()  # How do you extract weekday name?
# df['Month Name'] = df['Order Date'].dt.month_name()  # How do you extract month name?

# # 7. Calculate delivery days
# df['Delivery Days'] = (df['Ship Date'] - df['Order Date']).dt.days  # How do you calculate delivery days?

# # 8. Create business columns
# df['Profit Status'] = df['Profit'].apply(lambda x: 'Profit' if x > 0 else 'Loss')  # How do you create Profit Status?
# df['Sales Level'] = df['Sales'].apply(lambda x: 'High Sales' if x > 1000 else 'Low Sales')  # How do you create Sales Level?
# df['Discount Level'] = df['Discount'].apply(lambda x: 'High Discount' if x > 0.3 else 'Low Discount')  # How do you create Discount Level?
# df['Profit Margin'] = (df['Profit'] / df['Sales']) * 100  # How do you create Profit Margin?

# # 9. Select columns
# df['Sales']  # How do you select one column?
# df[['Sales', 'Profit']]  # How do you select multiple columns?
# df[['Customer Name', 'Product Name', 'Sales', 'Profit']]  # How do you select important columns?

# # 10. loc and iloc
# df.loc[:, ['Sales', 'Profit']]  # How do you select columns using loc?
# df.iloc[:, [17, 20]]  # How do you select Sales and Profit using iloc?
# df.iloc[0:5, 0:4]  # How do you select first 5 rows and first 4 columns?

# # 11. Filtering
# df[df['Segment'] == 'Consumer']  # How do you filter Consumer segment?
# df[df['Segment'] == 'Corporate']  # How do you filter Corporate segment?
# df[df['Segment'] == 'Home Office']  # How do you filter Home Office segment?
# df[df['Sales'] > 1000]  # How do you filter Sales greater than 1000?
# df[df['Sales'] < 100]  # How do you filter Sales less than 100?
# df[df['Profit'] > 0]  # How do you filter profitable orders?
# df[df['Profit'] < 0]  # How do you filter loss-making orders?
# df[df['Discount'] > 0.3]  # How do you filter high discount orders?
# df[df['Region'] == 'West']  # How do you filter West region?
# df[df['Region'] == 'East']  # How do you filter East region?
# df[df['Category'] == 'Furniture']  # How do you filter Furniture category?
# df[df['Category'] == 'Technology']  # How do you filter Technology category?
# df[df['Category'] == 'Office Supplies']  # How do you filter Office Supplies category?
# df[(df['Category'] == 'Furniture') & (df['Profit'] < 0)]  # How do you filter Furniture category with loss?
# df[(df['Discount'] > 0.3) & (df['Profit'] < 0)]  # How do you filter high discount loss orders?
# df[df['Region'].isin(['West', 'East'])]  # How do you filter West and East regions?

# # 12. Sorting
# df.sort_values(by='Sales')  # How do you sort Sales ascending?
# df.sort_values(by='Sales', ascending=False)  # How do you sort Sales descending?
# df.sort_values(by='Profit', ascending=False)  # How do you sort Profit descending?
# df.sort_values(by='Profit')  # How do you sort Profit ascending?
# df.sort_values(by='Sales', ascending=False).head(10)  # How do you find top 10 highest sales orders?
# df.sort_values(by='Profit', ascending=False).head(10)  # How do you find top 10 highest profit orders?
# df.sort_values(by='Profit').head(10)  # How do you find top 10 loss-making orders?

# # 13. Aggregation
# df['Sales'].sum()  # How do you find total sales?
# df['Profit'].sum()  # How do you find total profit?
# df['Quantity'].sum()  # How do you find total quantity?
# df['Sales'].mean()  # How do you find average sales?
# df['Profit'].mean()  # How do you find average profit?
# df['Sales'].max()  # How do you find maximum sales?
# df['Sales'].min()  # How do you find minimum sales?
# df['Profit'].max()  # How do you find maximum profit?
# df['Profit'].min()  # How do you find minimum profit?
# df['Sales'].median()  # How do you find median sales?
# df['Sales'].std()  # How do you find standard deviation of sales?
# df[['Sales', 'Profit', 'Quantity']].sum()  # How do you find total Sales, Profit, Quantity together?

# # 14. Value counts and unique values
# df['Category'].unique()  # How do you check unique categories?
# df['Category'].nunique()  # How do you count unique categories?
# df['Category'].value_counts()  # How do you count orders by category?
# df['Region'].value_counts()  # How do you count orders by region?
# df['Segment'].value_counts()  # How do you count orders by segment?
# df['Ship Mode'].value_counts()  # How do you count orders by ship mode?
# df['Customer ID'].nunique()  # How do you count unique customers?
# df['Product ID'].nunique()  # How do you count unique products?

# # 15. GroupBy
# df.groupby('Region')['Sales'].sum()  # How do you find region-wise sales?
# df.groupby('Region')['Profit'].sum()  # How do you find region-wise profit?
# df.groupby('Region')[['Sales', 'Profit']].sum()  # How do you find region-wise sales and profit?
# df.groupby('Category')['Sales'].sum()  # How do you find category-wise sales?
# df.groupby('Category')['Profit'].sum()  # How do you find category-wise profit?
# df.groupby('Category')[['Sales', 'Profit']].sum()  # How do you find category-wise sales and profit?
# df.groupby('Sub-Category')['Sales'].sum()  # How do you find sub-category-wise sales?
# df.groupby('Sub-Category')['Profit'].sum()  # How do you find sub-category-wise profit?
# df.groupby('Segment')['Sales'].sum()  # How do you find segment-wise sales?
# df.groupby('Segment')['Profit'].sum()  # How do you find segment-wise profit?
# df.groupby('State')['Sales'].sum()  # How do you find state-wise sales?
# df.groupby('State')['Profit'].sum()  # How do you find state-wise profit?
# df.groupby('City')['Sales'].sum()  # How do you find city-wise sales?
# df.groupby('City')['Profit'].sum()  # How do you find city-wise profit?
# df.groupby('Customer Name')['Sales'].sum()  # How do you find customer-wise sales?
# df.groupby('Customer Name')['Profit'].sum()  # How do you find customer-wise profit?
# df.groupby('Product Name')['Sales'].sum()  # How do you find product-wise sales?
# df.groupby('Product Name')['Profit'].sum()  # How do you find product-wise profit?
# df.groupby(['Region', 'Category'])[['Sales', 'Profit']].sum()  # How do you find sales and profit by Region and Category?

# # 16. Top and bottom analysis
# df.groupby('Region')['Sales'].sum().sort_values(ascending=False).head(1)  # Which region has highest sales?
# df.groupby('Region')['Profit'].sum().sort_values(ascending=False).head(1)  # Which region has highest profit?
# df.groupby('Region')['Profit'].sum().sort_values().head(1)  # Which region has lowest profit?
# df.groupby('Category')['Sales'].sum().sort_values(ascending=False).head(1)  # Which category has highest sales?
# df.groupby('Category')['Profit'].sum().sort_values(ascending=False).head(1)  # Which category has highest profit?
# df.groupby('Sub-Category')['Sales'].sum().sort_values(ascending=False).head(10)  # Which are top 10 sub-categories by sales?
# df.groupby('Sub-Category')['Profit'].sum().sort_values(ascending=False).head(10)  # Which are top 10 sub-categories by profit?
# df.groupby('Sub-Category')['Profit'].sum().sort_values().head(10)  # Which are loss-making sub-categories?
# df.groupby('Product Name')['Sales'].sum().sort_values(ascending=False).head(10)  # How do you identify top 10 products by sales?
# df.groupby('Product Name')['Profit'].sum().sort_values(ascending=False).head(10)  # How do you identify profitable products?
# df.groupby('Product Name')['Profit'].sum().sort_values().head(10)  # How do you identify loss-making products?
# df.groupby('Customer Name')['Sales'].sum().sort_values(ascending=False).head(10)  # How do you identify top 10 customers by sales?
# df.groupby('Customer Name')['Profit'].sum().sort_values(ascending=False).head(10)  # How do you identify top 10 customers by profit?
# df.groupby('State')['Sales'].sum().sort_values(ascending=False).head(10)  # Which states have highest sales?
# df.groupby('State')['Profit'].sum().sort_values(ascending=False).head(10)  # Which states have highest profit?
# df.groupby('State')['Profit'].sum().sort_values().head(10)  # Which states have lowest profit?
# df.groupby('City')['Sales'].sum().sort_values(ascending=False).head(10)  # Which cities have highest sales?
# df.groupby('City')['Profit'].sum().sort_values(ascending=False).head(10)  # Which cities have highest profit?
# df.groupby('City')['Profit'].sum().sort_values().head(10)  # Which cities have lowest profit?

# # 17. Date analysis
# df.groupby('Year')['Sales'].sum()  # How do you find yearly sales?
# df.groupby('Year')['Profit'].sum()  # How do you find yearly profit?
# df.groupby('Month')['Sales'].sum()  # How do you find monthly sales?
# df.groupby('Month')['Profit'].sum()  # How do you find monthly profit?
# df.groupby(['Year', 'Month'])['Sales'].sum()  # How do you find year-month sales trend?
# df.groupby(['Year', 'Month'])['Profit'].sum()  # How do you find year-month profit trend?

# # 18. Discount analysis
# df['Discount'].mean()  # How do you find average discount?
# df['Discount'].max()  # How do you find maximum discount?
# df.groupby('Discount')['Sales'].sum()  # How do you find sales by discount?
# df.groupby('Discount')['Profit'].sum()  # How do you find profit by discount?
# df.groupby('Discount')[['Sales', 'Profit']].sum()  # How do you check discount impact?
# df[(df['Discount'] > 0.3) & (df['Profit'] < 0)]  # How do you find high discount loss orders?
# df.groupby('Discount')['Profit'].sum().sort_values()  # Which discount level gives highest loss?

# # 19. Shipping analysis
# df['Ship Mode'].value_counts()  # Which ship mode is used most?
# df.groupby('Ship Mode')['Sales'].sum().sort_values(ascending=False)  # Which ship mode has highest sales?
# df.groupby('Ship Mode')['Profit'].sum().sort_values(ascending=False)  # Which ship mode has highest profit?
# df.groupby('Ship Mode')['Profit'].sum().sort_values()  # Which ship mode has lowest profit?
# df.groupby('Ship Mode')[['Sales', 'Profit']].sum()  # How do you find ship mode-wise sales and profit?
# df.groupby('Ship Mode')['Delivery Days'].mean()  # How do you find average delivery days by ship mode?
# df[df['Delivery Days'] > 5]  # Which orders took more than 5 days to deliver?

# # 20. String functions
# df['Customer Name'].str.upper()  # How do you convert customer names to uppercase?
# df['Customer Name'].str.lower()  # How do you convert customer names to lowercase?
# df['Product Name'].str.strip()  # How do you remove spaces from Product Name?
# df[df['Product Name'].str.contains('Table', case=False, na=False)]  # How do you find products containing Table?
# df[df['Product Name'].str.contains('Chair', case=False, na=False)]  # How do you find products containing Chair?
# df[df['Product Name'].str.contains('Phone', case=False, na=False)]  # How do you find products containing Phone?
# df['Product Name'].str.split().str[0]  # How do you extract first word from Product Name?
# df['Customer Name'].str.split().str[0]  # How do you extract first name from Customer Name?

# # 21. Pivot table
# pd.pivot_table(df, values='Sales', index='Region', columns='Category', aggfunc='sum')  # How do you create Region and Category sales pivot?
# pd.pivot_table(df, values='Profit', index='Region', columns='Category', aggfunc='sum')  # How do you create Region and Category profit pivot?
# pd.pivot_table(df, values='Sales', index='Segment', columns='Category', aggfunc='sum')  # How do you create Segment and Category sales pivot?
# pd.pivot_table(df, values='Profit', index='Segment', columns='Category', aggfunc='sum')  # How do you create Segment and Category profit pivot?

# # 22. Correlation
# df[['Sales', 'Quantity', 'Discount', 'Profit']].corr()  # How do you find correlation between numerical columns?
# df[['Sales', 'Profit']].corr()  # How do you find correlation between Sales and Profit?
# df[['Discount', 'Profit']].corr()  # How do you find correlation between Discount and Profit?

# # 23. Visualization
# df.groupby('Category')['Sales'].sum().plot(kind='bar')  # How do you plot category-wise sales?
# df.groupby('Category')['Profit'].sum().plot(kind='bar')  # How do you plot category-wise profit?
# df.groupby('Region')['Sales'].sum().plot(kind='bar')  # How do you plot region-wise sales?
# df.groupby('Region')['Profit'].sum().plot(kind='bar')  # How do you plot region-wise profit?
# df.groupby('Month')['Sales'].sum().plot(kind='line')  # How do you plot monthly sales trend?
# df.groupby('Year')['Sales'].sum().plot(kind='line')  # How do you plot yearly sales trend?
# df.plot(x='Discount', y='Profit', kind='scatter')  # How do you plot Discount vs Profit?
# df['Sales'].plot(kind='hist')  # How do you plot Sales distribution?
# df['Profit'].plot(kind='hist')  # How do you plot Profit distribution?

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID 1       9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID 1       9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [92]:
 df.rename(columns = {'Row ID':'Row ID 1'},inplace = True)

In [93]:
df.columns

Index(['Row ID 1', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [95]:
df.isnull().sum()

Row ID 1         0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [96]:
df.isnull().sum().sum()

0

In [98]:
df.duplicated().sum()

0

In [102]:
df.drop_duplicates(inplace=True)

In [106]:
df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True)
print(df)

      Row ID 1        Order ID Order Date   Ship Date       Ship Mode  \
0            1  CA-2016-152156 2016-11-08  11/11/2016    Second Class
1            2  CA-2016-152156 2016-11-08  11/11/2016    Second Class
2            3  CA-2016-138688 2016-06-12   16/6/2016    Second Class
3            4  US-2015-108966 2015-10-11  18/10/2015  Standard Class
4            5  US-2015-108966 2015-10-11  18/10/2015  Standard Class
...        ...             ...        ...         ...             ...
9989      9990  CA-2014-110422 2014-01-21   23/1/2014    Second Class
9990      9991  CA-2017-121258 2017-02-26    3/3/2017  Standard Class
9991      9992  CA-2017-121258 2017-02-26    3/3/2017  Standard Class
9992      9993  CA-2017-121258 2017-02-26    3/3/2017  Standard Class
9993      9994  CA-2017-119914 2017-05-04    9/5/2017    Second Class

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson
1       CG-12520       Claire Gute   Consumer  United States        Henderson
2       DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles
3       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
4       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
...          ...               ...        ...            ...              ...
9989    TB-21400  Tom Boeckenhauer   Consumer  United States            Miami
9990    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9991    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9992    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9993    CC-12220      Chris Cortes   Consumer  United States      Westminster

      ... Postal Code  Region       Product ID         Category Sub-Category  \
0     ...       42420   South  FUR-BO-10001798        Furniture    Bookcases
1     ...       42420   South  FUR-CH-10000454        Furniture       Chairs
2     ...       90036    West  OFF-LA-10000240  Office Supplies       Labels
3     ...       33311   South  FUR-TA-10000577        Furniture       Tables
4     ...       33311   South  OFF-ST-10000760  Office Supplies      Storage
...   ...         ...     ...              ...              ...          ...
9989  ...       33180   South  FUR-FU-10001889        Furniture  Furnishings
9990  ...       92627    West  FUR-FU-10000747        Furniture  Furnishings
9991  ...       92627    West  TEC-PH-10003645       Technology       Phones
9992  ...       92627    West  OFF-PA-10004041  Office Supplies        Paper
9993  ...       92683    West  OFF-AP-10002684  Office Supplies   Appliances

                                           Product Name     Sales  Quantity  \
0                     Bush Somerset Collection Bookcase  261.9600         2
1     Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3
2     Self-Adhesive Address Labels for Typewriters b...   14.6200         2
3         Bretford CR4500 Series Slim Rectangular Table  957.5775         5
4                        Eldon Fold 'N Roll Cart System   22.3680         2
...                                                 ...       ...       ...
9989                             Ultra Door Pull Handle   25.2480         3
9990  Tenex B1-RE Series Chair Mats for Low Pile Car...   91.9600         2
9991                              Aastra 57i VoIP phone  258.5760         2
9992  It's Hot Message Books with Stickers, 2 3/4" x 5"   29.6000         4
9993  Acco 7-Outlet Masterpiece Power Center, Wihtou...  243.1600         2

      Discount    Profit
0         0.00   41.9136
1         0.00  219.5820
2         0.00    6.8714
3         0.45 -383.0310
4         0.20    2.5164
...        ...       ...
9989      0.20    4.1028
9990      0.00   15.6332
9991      0.20   19.3932
9992      0.00   13.3200
9993      0.00   72.9480

[9994 rows x 21 columns]

In [112]:
from sklearn.impute import KNNImputer

In [110]:
pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in c:\programdata\anaconda3\lib\site-packages (1.3.0)
Requirement already satisfied: numpy>=1.17.3 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn) (1.24.3)
Requirement already satisfied: scipy>=1.5.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn) (1.11.1)
Requirement already satisfied: joblib>=1.1.1 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn) (2.2.0)
Note: you may need to restart the kernel to use updated packages.

DEPRECATION: Loading egg at c:\programdata\anaconda3\lib\site-packages\vboxapi-1.0-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..